### ISSUE TITLE
Fix this pls

### ISSUE THREAD

**Issue by Hiho2950** [Tungstend/HMCL-PE#100]
Pls fix this
![Screenshot_20221012-203606_HMCL-PE](https://user-images.githubusercontent.com/109638489/195432821-fe74a3c4-172a-49e7-b0ea-c233cf42b098.jpg)
![Screenshot_20221012-203559_HMCL-PE](https://user-images.githubusercontent.com/109638489/195432879-afc04a26-6b5d-4400-89eb-1c48f16bdba3.jpg)
I got this bug in 1.16.5 forge and vanilla too,my smartphone is samsung a12 nacho, android version:11.i dont know what is the cause of this bug.

**Comment by LegacyGamerHD** [comment]
Invalid template and not our issue but holy gl4es

**Comment by Hiho2950** [comment]
> Invalid template and not our issue but holy gl4es

I got this issue with virgl

**Comment by LegacyGamerHD** [comment]
> > Invalid template and not our issue but holy gl4es
> 
> I got this issue with virgl

dont use virgl

**Comment by Hiho2950** [comment]
But with holy gl4es it crash

**Comment by Hiho2950** [comment]
I will retry

**Comment by Hiho2950** [comment]
> > > Invalid template and not our issue but holy gl4es
> > 
> > 
> > I got this issue with virgl
> 
> dont use virgl

I have use holy gl4ed it work but crash in the loading screen

**Comment by LegacyGamerHD** [comment]
we have no controll on render as the source code is not ours

**Comment by Hiho2950** [comment]
> we have no controll on render as the source code is not ours

Ok
I think becuase you use pojavlauncher and boat render

**Comment by Hiho2950** [comment]
1.12.2 and below work correctly but other versions work with bugs

**Comment by Thollp** [comment]
> But with holy gl4es it crash

Create doesn't work on GL4ES, because it doesn't support OpenGL 3.2+ features.
