### ISSUE TITLE
Add zink renderer

### ISSUE THREAD

**Issue by Thollp** [Tungstend/HMCL-PE#113]
**Is your feature request related to a problem? Please describe.**
Yes, it's #100

**Describe the solution you'd like**
Just add a zink renderer. Because its the only working renderer that work properly on my phone, it even work in any version. (I know because I once play pojavlauncher)

**Describe alternatives you've considered**
*No alternatives I've considered*

**Additional context**
*Nah*

**Comment by LegacyGamerHD** [comment]
#112
