### ISSUE TITLE
Not Compatible with Android 5

### ISSUE THREAD

**Issue by SrAb4elha** [Tungstend/HMCL-PE#13]
Everytime I try to install the launcher it says it's not compatible

Device:

Galaxy j1 2016 
RAM memory: 1gb Ram
Android 5.1.1

![Screenshot_2022-08-29-13-42-55](https://user-images.githubusercontent.com/86976758/187252211-bd62ac0d-4f71-486f-bac7-f23bd94698aa.png)

**Comment by LegacyGamerHD** [comment]
Won't be compatible any time soon
