### ISSUE TITLE
fix this pls

### ISSUE THREAD

**Issue by Hiho2950** [Tungstend/HMCL-PE#24]
**Describe the bug**
when i start minecraft 1.16.5 forge with holy GL4ES the game crash
**To Reproduce**
start minecraft 1.16.5 forge

**Smartphone (please complete the following information):**
 - Device: [e.g. samsung a12 nacho]
 - OS: [e.g. Android 11]

**Additional context**
when i use virglrenderer, the game dont crash but i like Holy GL4ES because i got more fps than the virglrenderer

**Comment by LegacyGamerHD** [comment]
invalid
