### ISSUE TITLE
Java 17 not download 

### ISSUE THREAD

**Issue by KumarAyush927** [Tungstend/HMCL-PE#3]
I'm trying to install java 17 in hmcl pe but it's keep saying download failed try again

**Comment by SlawCH** [comment]
Link java 17 to hmcl pe pleass

**Comment by Hiho2950** [comment]
when i install hcml pe i got java 17 are already installed

**Comment by ENDERGAMING321** [comment]
Hmcl pe 32

**Comment by Xn294541** [comment]
> 
https://github.com/Tungstend/HMCL-PE/issues/3#issuecomment-1223965903

**Comment by Turselda** [comment]
Как скачать джава 17 на hmcl

**Comment by Turselda** [comment]
> 

Тоже самое , как это решить , похоже разрабы на хмцл положить гигантский хер

**Comment by Gleb-spe** [comment]
who has a link to 17 java for a single installations
