### ISSUE TITLE
Please fix In 32bit/aarch32 Devices Is when I play its Stuck at loading like infinity loading

### ISSUE THREAD

**Issue by jethro527** [Tungstend/HMCL-PE#30]
**Describe the bug**

**To Reproduce**
1. Go to '.Tap Any version of game.'
2. Click on '.click on play.'
3. THEN IT WILL STUCK '.Infinity loading.'

**Paste logs here**

<details>
<summary>log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Itel P36
 - OS: Android 9
 - Version :
 -Device Architecture: 32bit
**Additional context**

**Comment by Dnvbdbd** [comment]
Yes
