### ISSUE TITLE
in the last update when i start the game it shuts down

### ISSUE THREAD

**Issue by omerfarukpro** [Tungstend/HMCL-PE#33]
**Describe the bug**
in the last update when i start the game it shuts down

**To Reproduce**

**Paste logs here**

<details>
<summary>log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. HUAWEI Mate 50]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by LegacyGamerHD** [comment]
latest action build is not ready yet
