### ISSUE TITLE
Not working in pakage erorr android 6 mydevice:oppo f3 plus 4gb ram 64bit

### ISSUE THREAD

**Issue by Johncarlo030311** [Tungstend/HMCL-PE#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Johncarlo030311** [comment]
Pls make a hello launcher for all phone versions

**Comment by LegacyGamerHD** [comment]
no android 6 support

**Comment by sahidur2007** [comment]
App not installed problem in Android 8.1.0 32bit
