### ISSUE TITLE
please fix,I can't get into the game

### ISSUE THREAD

**Issue by Hdhdhhdf** [Tungstend/HMCL-PE#43]
- Device: [e.g. Realme C11 2021]
 - OS: [e.g. Android 11]

**Comment by fahimgaming** [comment]
which is your Phone Bit 32 or 64

**Comment by Hdhdhhdf** [comment]
> 

my phone is 32bit

**Comment by MatheusTGamerPro** [comment]
But what is the error that displays when entering the Game?

**Comment by LegacyGamerHD** [comment]
invalid
