### ISSUE TITLE
Please give multi agriculture and Java 17 32 bit please please 

### ISSUE THREAD

**Issue by Varunkrl** [Tungstend/HMCL-PE#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tttghkg** [comment]
我的世界1.17+好像不能在java17 32位上运行

**Comment by Varunkrl** [comment]
Please

**Comment by LegacyGamerHD** [comment]
its already in the latest dev build
