### ISSUE TITLE
32 bit can't download 2021 and 2022 or another version of forge

### ISSUE THREAD

**Issue by Davicoderliner** [Tungstend/HMCL-PE#55]
I'm found a bug at forge I'm start to download forge at a 32 bit for 1.12.2 this give this error
![Screenshot_20220913-174738](https://user-images.githubusercontent.com/112778327/190006131-d23942c9-a73a-4392-8a4e-09459bdbee8c.png)

Have solution to fix this error?

**Comment by LegacyGamerHD** [comment]
known issue

**Comment by Davicoderliner** [comment]
Fix this soon for me

**Comment by LegacyGamerHD** [comment]
> Fix this soon for me

nope if you pay us

**Comment by LegacyGamerHD** [comment]
then we can do it faster

**Comment by Davicoderliner** [comment]
Ok

**Comment by Davicoderliner** [comment]
I'm will be patient to fix this bug
