### ISSUE TITLE
提示清楚与HMCL和HMCL-PE的关系

### ISSUE THREAD

**Issue by zkitefly** [Tungstend/HMCL-PE#66]
建议在第一次打开程序时提示清楚HMCL和HMCL-PE的关系

有一部分人在使用HMCL-PE时误以为是HMCL的分支，但其实并不是

见到过有人在HMCL的issues问在哪里下载HMCL-PE（

类似这样的还很多（

希望能做出提示

**Comment by Tungstend** [comment]
彳亍

**Comment by AtlasGaming175** [comment]
I request that hmclpe support on android version 6.0.1 samsung j2 prime

**Comment by LegacyGamerHD** [comment]
> I request that hmclpe support on android version 6.0.1 samsung j2 prime

There won't be 6.0 support get a new device
