### ISSUE TITLE
Game crashes on launch of any version

### ISSUE THREAD

**Issue by FreeFormGaming** [Tungstend/HMCL-PE#68]
On my Samsung galaxy a13 5G HMCL-PE crashes when I try to launch any version of minecraft why is this?

**Comment by Gta5mcmobi** [comment]
So sad my too crashes game when I launch g😭😭😭😭😭😭😭😭😭😭😭😱😭

**Comment by Gta5mcmobi** [comment]
There bad they closed report 😡😡😡😡😡😡😡😡😡😡😡😡🤮🤬💩💩💩🔫🔫🔫🔫🔫🔫🔫

**Comment by LegacyGamerHD** [comment]
> There bad they closed report 😡😡😡😡😡😡😡😡😡😡😡😡🤮🤬💩💩💩🔫🔫🔫🔫🔫🔫🔫

you knwo why i closed it no log  and if think we can fix it blindly no we cant

**Comment by FreeFormGaming** [comment]
> > There bad they closed report 😡😡😡😡😡😡😡😡😡😡😡😡🤮🤬💩💩💩🔫🔫🔫🔫🔫🔫🔫
> 
> you knwo why i closed it no log and if think we can fix it blindly no we cant

I could not find the log
