### ISSUE TITLE
java 17 aarch64 (arm64) broken

### ISSUE THREAD

**Issue by mcagabe19** [Tungstend/HMCL-PE#7]
![Screenshot_20220827-205411_HMCL-PE](https://user-images.githubusercontent.com/82843871/187050589-9f1a1fa2-95f0-4333-99f5-3103b08fd4b1.png)
bug so simple to fix (i think)

**Comment by LegacyGamerHD** [comment]
Is not broken

**Comment by mcagabe19** [comment]
bruh then why i cant use java 17?

**Comment by LegacyGamerHD** [comment]
> bruh then why i cant use java 17?

because you use it on a to old version
