### ISSUE TITLE
Virgil render crash and optifine not installed 

### ISSUE THREAD

**Issue by Bhavesh6295** [Tungstend/HMCL-PE#77]
**Describe the bug**

**To Reproduce**

**Paste logs here**

<details>
<summary>log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. HUAWEI Mate 50]
 - OS: [e.g. Android 10]

**Additional context**

>

**Comment by ALiF999013** [comment]
help me i'm playing hmcl-pe it's error Please help me :(

**Comment by LegacyGamerHD** [comment]
Invalid no log
