### ISSUE TITLE
[Question] What is the Official repository of HMCL-PE? (two repositories)

### ISSUE THREAD

**Issue by MatheusTGamerPro** [Tungstend/HMCL-PE#79]
I noticed that it contains two HMCL-PE repositories, one is "HMCL-PE-CN" and this one, which one are you developing?

**Comment by Tungstend** [comment]
Both, due to the special network environment in mainland China, I split the software into Chinese version and global version

**Comment by MatheusTGamerPro** [comment]
got it, thanks for replying.
