### ISSUE TITLE
🤔🤐🤨😐😑😶🙄😬😮‍💨🤥😔😪🤤🤒🤕🤢🤮🤧🥵🥶🥴😵😵‍💫🤯😥😢😭😭😭😭😭😭😭😖😣😞😓😩😫😤😡😠🤬😈👿💀☠️💩💩💩💩💩💩💘💘💘💘💘💔💔💔💔

### ISSUE THREAD

**Issue by Gta5mcmobi** [Tungstend/HMCL-PE#85]
**Describe the bug**

**To Reproduce**

**Paste logs here**

<details>
<summary>log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. HUAWEI Mate 50]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by Gta5mcmobi** [comment]
Fast reply me

**Comment by Gta5mcmobi** [comment]
Fast fast fast

**Comment by Gta5mcmobi** [comment]
Fast fast fast reply

**Comment by Gta5mcmobi** [comment]
Fast fast fast

**Comment by Gta5mcmobi** [comment]
😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😤😡🤬😈👿💀☠️👽🙀😿😾💘💘

**Comment by LegacyGamerHD** [comment]
your baned from repo
