### ISSUE TITLE
添加 HiPer 支持

### ISSUE THREAD

**Issue by zkitefly** [Tungstend/HMCL-PE#86]
# 建议

建议添加 HiPer 联机模块的支持

# 好处
这样可以带来一个好处，那能够与电脑端的HMCL互联

这个其实也是hmclpe联机页面的一个痛点，不能跟电脑端互相联机

在最近HMCL添加了 HiPer 的支持，目前PCL2也正在做适配

相关开发帮助和授权，加入Q群交谈：235256586

**Comment by Tungstend** [comment]
这玩意支持Android平台么，我记得之前用cato好像不支持Android的

**Comment by zkitefly** [comment]
> 这玩意支持Android平台么，我记得之前用cato好像不支持Android的

有的。建议加入群聊，和群主说说

![Screenshot_20221001-131827](https://user-images.githubusercontent.com/64117916/193394008-dab67dbd-c789-4af3-a8f3-78641ed5fe01.jpg)

**Comment by Tungstend** [comment]
已经适配，就差ui了
