### ISSUE TITLE
Glitch on can't click 7 - 9 slot box

### ISSUE THREAD

**Issue by kedrick021** [Tungstend/HMCL-PE#9]
1. Open hello launcher
2. Start hello launcher
3. Create world
4. 1 - 6 slot box can click
5. But 7 - 9 slot box can't click

**Comment by tigerbrocode** [comment]
Hello launcher 💀

**Comment by DodongPojav11** [comment]
Same problem

**Comment by DodongPojav11** [comment]
Same problem

**Comment by MatheusTGamerPro** [comment]
Adjust the size of the HUD
