### ISSUE TITLE
the mod cant be used

### ISSUE THREAD

**Issue by WalkerNotFound** [Tungstend/HMCL-PE#94]
**Describe the bug**

**To Reproduce**

**Paste logs here**

<details>
<summary>log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. HUAWEI Mate 50]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by LegacyGamerHD** [comment]
no log and invalid template
